before_script:
  - docker info
  - git clean -ffdx

stages:
  - build
  - test
  - production
  - log

hakka_service_image:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service .
    - docker push $CI_REGISTRY/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service

sonarqube_scan_project:
  stage: test
  # sonarqube掃描快取資料
  cache: 
    key: ${CI_COMMIT_REF_SLUG}-sonarqube
    paths:
      - .sonar-cache/
  # 允許在資安掃描時失敗
  allow_failure: true
  script:
    - echo "Prepare Sonarqube Scan - Server ${SONAR_HOST_URL}" 
    - docker run --rm -e SONAR_HOST_URL=${SONAR_HOST_URL} 
      -v "${PWD}:/usr/src" -v ${PWD}/.sonar-cache:/opt/sonar-scanner/.sonar/cache 
      sonarsource/sonar-scanner-cli

deploy_service:
  stage: production
  needs: ["hakka_service_image"]
  script:
    - ls 
    - docker-compose up -d --build
    #- docker run my-docker-image /script/to/run/tests

service_log:
  stage: log
  needs: ["deploy_service"]
  script:
    - docker-compose ps 
    - docker-compose logs
