before_script:
  - docker info

stages:
  - production

show_docker_info:
  stage: production
  script:
    - ls 
    - docker-compose up -d --build
    #- docker run my-docker-image /script/to/run/tests
