before_script:
  - docker info

stages:
  - build
  - production

hakka_service_image:
  stage: build
  script:
    - docker build -t registry.406.csie.nuu.edu.tw/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service .
    - docker push registry.406.csie.nuu.edu.tw/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service

deploy_service:
  stage: production
  script:
    - ls 
    - docker-compose up -d --build
    #- docker run my-docker-image /script/to/run/tests
