before_script:
  - docker info

stages:
  - build
  - test
  - production
  - log

hakka_service_image:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service .
    - docker push $CI_REGISTRY/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service

sonarqube_scan_project:
  stage: test
  script:
    - echo "準備進行sonarqube資安掃描 Server: ${SONAR_HOST_URL}"
    - docker run --rm --user="$(id -u):$(id -g)" -e SONAR_HOST_URL=http://${SONAR_HOST_URL} -v "${PWD}:/usr/src" sonarsource/sonar-scanner-cli

deploy_service:
  stage: production
  needs: ["hakka_service_image"]
  script:
    - ls 
    - docker-compose up -d --build
    #- docker run my-docker-image /script/to/run/tests

service_log:
  stage: log
  needs: ["deploy_service"]
  script:
    - docker-compose ps 
    - docker-compose logs
