# 客家語音快速獨立擴充系統
version: '2.3'
services:
    # 模型alpha
    model-alpha:
        #build: ./
        image: registry.406.csie.nuu.edu.tw/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service:latest
        restart: always
        environment:
            - VIRTUAL_HOST=alpha.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_HOST=alpha.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
            - VIRTUAL_PORT=80
            # 網頁顯示參數
            - CLASS_COUNT=10
            - SAMPLE_RATE=16000
            - SOUND_LENGTH=25
            - STEP=25
        volumes:
            - './模型/alpha/conv_labels_1.txt:/labels.txt:rw'
            - './模型/alpha/my_frozen_graph1.pb:/graph.pb:rw'
    
    # 模型beta
    model-beta:
        #build: ./
        image: registry.406.csie.nuu.edu.tw/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service:latest
        restart: always
        environment:
            - VIRTUAL_HOST=beta.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_HOST=beta.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
            - VIRTUAL_PORT=80
            # 網頁顯示參數
            - CLASS_COUNT=10
            - SAMPLE_RATE=16000
            - SOUND_LENGTH=25
            - STEP=25
        volumes:
            - './模型/beta/conv_labels_2.txt:/labels.txt:rw'
            - './模型/beta/my_frozen_graph2.pb:/graph.pb:rw'

    # 模型charlie
    model-charlie:
        #build: ./
        image: registry.406.csie.nuu.edu.tw/hakka-405/docker-gpu-hakka-speech-command-api-service/hakka-service:latest
        restart: always
        environment:
            - VIRTUAL_HOST=charlie.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_HOST=charlie.hakka.csie.nuu.edu.tw
            - LETSENCRYPT_EMAIL=m0724001@gm.nuu.edu.tw
            - VIRTUAL_PORT=80
            # 網頁顯示參數
            - CLASS_COUNT=10
            - SAMPLE_RATE=16000
            - SOUND_LENGTH=25
            - STEP=25
        volumes:
            - './模型/charlie/conv_labels_3.txt:/labels.txt:rw'
            - './模型/charlie/my_frozen_graph3.pb:/graph.pb:rw'
